apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rude-tyrannosaurus-go 
  janus-idp.io/tekton: rude-tyrannosaurus-go
  backstage.io/kubernetes-id: rude-tyrannosaurus-go
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: rude-tyrannosaurus-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  