apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rude-tyrannosaurus-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rude-tyrannosaurus-go 
  name: rude-tyrannosaurus-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rude-tyrannosaurus-go 
